---
additionalMemory: 6144
javaVersion: "11"
preBuildScript: |
    export JDK_16=/lib/jvm/java-1.8.0
    export JDK_17=/lib/jvm/java-1.8.0
    export JDK_18=/lib/jvm/java-1.8.0
    export JDK_9=/lib/jvm/java-11
    export DISABLE_JBS_REPOSITORY_PLUGIN=true
repositories:
  - "all"
  - "intellij-releases"
  - "intellij-dependencies"
additionalArgs:
  - "-Pkotlin.build.isObsoleteJdkOverrideEnabled=true"
  - "-Pmaven.repository.mirror=$(CACHE_URL)"
